package com.joohnq.propertiesrentalapp.model.entities

import androidx.room.Entity
import com.joohnq.propertiesrentalapp.util.Constants

@Entity(tableName = Constants.DATABASE_TABLE_HOME_PROPERTIES)
data class PropertyItem(
    val address: String,
    val bathrooms: Int,
    val contactInfo: ContactInfo,
    val country: String,
    val description: String,
    val detailedType: DetailedType,
    val district: String,
    val exterior: Boolean,
    val externalReference: String,
    val favourite: Boolean,
    val features: Features,
    val floor: String,
    val has360: Boolean,
    val has3DTour: Boolean,
    val hasLift: Boolean,
    val hasPlan: Boolean,
    val hasStaging: Boolean,
    val hasVideo: Boolean,
    val highlight: Highlight,
    val labels: List<Label>,
    val latitude: Double,
    val locationId: String,
    val longitude: Double,
    val multimedia: Multimedia,
    val municipality: String,
    val neighborhood: String,
    val newDevelopment: Boolean,
    val newProperty: Boolean,
    val numPhotos: Int,
    val operation: Operation,
    val preferenceHighlight: Boolean,
    val price: Double,
    val priceByArea: Double,
    val propertyCode: String,
    val propertyType: String,
    val province: String,
    val rooms: Int,
    val showAddress: Boolean,
    val size: Double,
    val status: String,
    val suggestedTexts: SuggestedTexts,
    val thumbnail: String,
    val topHighlight: Boolean,
    val topNewDevelopment: Boolean,
    val topPlus: Boolean,
    val urgentVisualHighlight: Boolean,
    val url: String,
    val visualHighlight: Boolean
)